### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by madmaxgrey** [Techpure2013/RS3QuestBuddy#17]
is this still being updated and will it be avaliable on alt1 third party plugins page?
as i am unsure if this is safe or not

**Comment by Techpure2013** [comment]
@madmaxgrey  It will continue to be updated. So far only thing to do is update the images for the quests which the progress is 67/346.
It hasnt been updated recently because lack of motivation and burnout since I and another (shes taking a break) has been at it for months and months. any contributors for images relatiing to steps in the quest will be cited in the quest folder its located in.

**Comment by madmaxgrey** [comment]
kool thank you
